### ISSUE TITLE
Latex Error: unkown graphics extension .svg

### ISSUE THREAD

**Issue by skhadrao** [yihui/tinytex#199]
Hello,

I'm using tintex to produce pdf files using a markdown, here is the YAML of it 

```


---

title: "SOME TITLE"

output:

  pdf_document:

    dev: 'png'

    toc: no

header-includes:

- \usepackage{booktabs}

- \usepackage{longtable}

- \usepackage{array}

- \usepackage{multirow}

- \usepackage[table]{xcolor}

- \usepackage{wrapfig}

- \usepackage{float}

- \usepackage{colortbl}

- \usepackage{pdflscape}

- \usepackage{tabu}

- \usepackage{threeparttable}

- \usepackage{threeparttablex}

- \usepackage[normalem]{ulem}

- \usepackage{makecell}

---

```

I'm getting the error below 
![image](https://user-images.githubusercontent.com/43041852/79643017-2d6c2000-81a1-11ea-9a5b-58d20ac34a98.png)

When I remove the dev option in the YAML, the code run perfectly and produces pdf graphics.

Any help ?
---

By filing an issue to this repo, I promise that

- [ ] I have fully read the issue guide at https://yihui.org/issue/.
- [ ] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('tinytex')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('yihui/tinytex')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [ ] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by cderv** [comment]
Hi, 

By submitting an issue, you agreed to follow the issue guide. In your post, you did not provide information about the version of your packages and a complete reproducible example. 

With your code, I get another error when knitting
````r
---
title: "SOME TITLE"
output:
  pdf_document:
    dev: 'png'
    toc: no
header-includes:
  - \usepackage{booktabs}
  - \usepackage{longtable}
  - \usepackage{array}
  - \usepackage{multirow}
  - \usepackage[table]{xcolor}
  - \usepackage{wrapfig}
  - \usepackage{float}
  - \usepackage{colortbl}
  - \usepackage{pdflscape}
  - \usepackage{tabu}
  - \usepackage{threeparttable}
  - \usepackage{threeparttablex}
  - \usepackage[normalem]{ulem}
  - \usepackage{makecell}
---

# Test
````

```r
! LaTeX Error: Option clash for package xcolor.
```

I think this error is because you set `  - \usepackage[table]{xcolor}` whereas `xcolor` is already a used package in Pandoc Latex template. (see [list of packages](https://pandoc.org/MANUAL.html#creating-a-pdf) in pandoc manual. 

Can you try with the code above and produce a reproducible example ? 
I guess your _Restitution_ document contains more thant a Yaml header ? The error could become from your document content. If you have `.svg` in your document content, it is possible that the png graphic device does not know how to handle it, whereas the default pdf device does. I am not an expert in graphic devices, so just a wild guess. 

Hope it helps

**Comment by skhadrao** [comment]
@cderv THanks for your relpy, I removed ``` - \usepackage[table]{xcolor}``` but still have the svg error ``` ! LaTeX Error: Unknown graphics extension: .svg ```.

For the xcolor error, I don't know why you'r having it, I"m on pandoc 2.3 and not having it.


Here is the code which allows generating pdf 

```
fonction_pdf = function(college) {
  # # Code rmarkdown des documents pdf
  rmarkdown::render(
    input = "/home/skhadraoui/workspace/1-Programmes/Etape-7_Restitution_college_pdf.Rmd",
    output_format = "pdf_document",
    output_file = paste(
      "/home/skhadraoui/workspace/4-Restitutions/Restitution_College/",
      paste(code_operation, college, "Restitution",
            sep =
              "_"),
      ".pdf",
      sep = ""
    ),
    output_options = list(),
    encoding = "UTF-8",
    clean = FALSE,
    quiet = TRUE
  )
}

```


The rmd file in inout has this header 

```
---
title: "SOME TITLE"
output:
  pdf_document:
    dev: 'png'
    toc: no
header-includes:
  - \usepackage{booktabs}
  - \usepackage{longtable}
  - \usepackage{array}
  - \usepackage{multirow}
  - \usepackage[table]{xcolor}
  - \usepackage{wrapfig}
  - \usepackage{float}
  - \usepackage{colortbl}
  - \usepackage{pdflscape}
  - \usepackage{tabu}
  - \usepackage{threeparttable}
  - \usepackage{threeparttablex}
  - \usepackage[normalem]{ulem}
  - \usepackage{makecell}
---
```

and some texts inside, I still have this annonying svg error ?
