### ISSUE TITLE
Fail to create pdf with chinese characters in markdown by CTEX packages

### ISSUE THREAD

**Issue by ChenChingChih** [yihui/tinytex#223]
Hi, I faced the problem with create a pdf with Chinese characters, and I have already ask on [Rcommunity](https://community.rstudio.com/t/fail-to-create-a-pdf-with-chinese-charactors-in-rmarkdown/71536) and on  [liao961120 /ntuthesis](https://github.com/liao961120/ntuthesis/issues/17) github page for Rbookdown thesis writing. 
Also, I am not sures is it similar with the [Capital of Statistics, COS](https://d.cosx.org/d/421590-bookdowntex), #210 , #211 telling about similar things recently.
My code:
```
---
title: "中文／にほんご／韓國語"
author: "ME"
date: "2016年9月19日"
header-includes:
  - \usepackage{ctex}
output: 
  pdf_document:
    latex_engine: xelatex
---

中文
```

Error message I GOT:

```
"C:/Program Files/RStudio/bin/pandoc/pandoc" +RTS -K512m -RTS a.utf8.md --to latex --from markdown+autolink_bare_uris+tex_math_single_backslash --output a.tex --self-contained --highlight-style tango --pdf-engine xelatex --variable graphics --lua-filter "C:/R-4.0.1/library/rmarkdown/rmd/lua/pagebreak.lua" --lua-filter "C:/R-4.0.1/library/rmarkdown/rmd/lua/latex-div.lua" --include-in-header "C:\Users\CHINGC~1\AppData\Local\Temp\Rtmp8sfQ5G\rmarkdown-str376c2a7e1e35.html" --variable "geometry:margin=1in" 
output file: a.knit.md

! Undefined control sequence.
<argument> \__xeCJK_patch_microtype_get_slot: 

錯誤: LaTeX failed to compile a.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See a.log for more info.
停止執行
```
> sessionInfo()
R version 4.0.1 (2020-06-06)
Platform: x86_64-w64-mingw32/x64 (64-bit)
 Running under: Windows 10 x64 (build 18363)
Matrix products: default
locale:
[1] LC_COLLATE=Chinese (Traditional)_Taiwan.950  LC_CTYPE=Chinese (Traditional)_Taiwan.950   
[3] LC_MONETARY=Chinese (Traditional)_Taiwan.950 LC_NUMERIC=C                                
[5] LC_TIME=Chinese (Traditional)_Taiwan.950    
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
loaded via a namespace (and not attached):
 [1] compiler_4.0.1  bookdown_0.20   htmltools_0.5.0 tools_4.0.1     yaml_2.2.1     
 [6] tinytex_0.24.1  remotes_2.1.1   rmarkdown_2.3   knitr_1.29      xfun_0.15      
[11] digest_0.6.25   rlang_0.4.6     evaluate_0.14

However,  I use other packages in tex which could work!
```
---
title: "test"
author: "ME"
date: "2020/5/5"
header-includes:
  - \usepackage{fontspec} # use fontspec package
  - \usepackage{xeCJK}    # use xeCJK package
  - \setCJKmainfont{標楷體} # font for windows
output: 
  pdf_document: 
    latex_engine: xelatex
---
中文
englsih
```
I am doubt that ctex is not match with tinytex well now :thinking:
Is there any solution could fix it easily?such as by install a old version of tinytex so that it would match better with ctex or other cjk pakages?
I try to use the [way](https://yihui.org/tinytex/faq/) to install a older version with `tinytex::install_tinytex(repository = 'https://texlive.info/tlnet-archive/2019/12/31/tlnet')`, but got the error belows
```
Please quit and reopen your R session and IDE (if you are using one, such as RStudio or Emacs) and check if tinytex:::is_tinytex() is TRUE.
Warning messages:
1: In file.remove("TinyTeX/install-tl.log") :
  無法移除檔案 'TinyTeX/install-tl.log' ，原因是 'No such file or directory'
2: In in_dir(target, { :
  The repository https://texlive.info/tlnet-archive/2019/12/31/tlnet does not seem to be accessible. Reverting to the default CTAN mirror.

```

```
xfun::session_info('tinytex')
R version 4.0.1 (2020-06-06)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Locale:
  LC_COLLATE=Chinese (Traditional)_Taiwan.950  LC_CTYPE=Chinese (Traditional)_Taiwan.950   
  LC_MONETARY=Chinese (Traditional)_Taiwan.950 LC_NUMERIC=C                                
  LC_TIME=Chinese (Traditional)_Taiwan.950    

Package version:
  graphics_4.0.1  grDevices_4.0.1 stats_4.0.1     tinytex_0.24    tools_4.0.1     utils_4.0.1    
  xfun_0.15      
```

Thanks for helping me!
