### ISSUE TITLE
Problem installing new packages

### ISSUE THREAD

**Issue by PenelopeLQ** [yihui/tinytex#53]
Hi! I'm running into this particular problem several times with different packages. For example, I'm trying to install tocloft and I used to be able to include this package in header as:
`header_includes:`
`    - \usepackage{tocloft}`
and the new package can be automatically installed.

But now I keep running into this problem:

> tlmgr search --file --global '/tocloft.sty'
Trying to automatically install missing LaTeX packages...
tlmgr install tocloft
tlmgr: package repository http://ftp.math.purdue.edu/mirrors/ctan.org/systems/texlive/tlnet (not verified: gpg unavailable)
tlmgr install: package already present: tocloft
tlmgr path add
tlmgr search --file --global '/tocloft.sty'
! LaTeX Error: File `tocloft.sty' not found.

> ! Emergency stop.
<read *> 

> Error:Failed to compile Knit1-all-lists.tex. See Knit1-all-lists.log for more info.
Execution halted

I'm using R 3.5.0 on OS X and RStudio 1.1.383.

Please help!

**Comment by yihui** [comment]
First, make sure you didn't install TinyTeX with `sudo`. Second, please provide [a minimal, self-contained, and reproducible example](https://yihui.name/en/2017/09/the-minimal-reprex-paradox/), and include your session info:

```r
xfun::session_info('rmarkdown')
```

I cannot reproduce your issue with this example:

````
---
title: "Test"
header-includes:
  - \usepackage{tocloft}
output:
  pdf_document: 
    keep_tex: yes
---

## R Markdown

This is an R Markdown document.
````
